version: '3.9'

services:
  web:
    env_file: .env
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - test_db
    restart: always
  
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${CONTAINER_DB_PORT}"
  
  redis:
    image: "redis:alpine"

  test_db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - test-db-data:/var/lib/postgresql/data
    ports:
      - "${TEST_DB_PORT}:${CONTAINER_DB_PORT}"

volumes:
  db-data:
  test-db-data: