"""add company role

Revision ID: d7eedb8afd28
Revises: c179972f3659
Create Date: 2023-03-16 16:50:16.287582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7eedb8afd28'
down_revision = 'c179972f3659'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('role', sa.Text(), nullable=True))
    op.create_index(op.f('ix_members_role'), 'members', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_role'), table_name='members')
    op.drop_column('members', 'role')
    # ### end Alembic commands ###
